//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASCOM.Optec.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Defaults : global::System.Configuration.ApplicationSettingsBase {
        
        private static Defaults defaultInstance = ((Defaults)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Defaults())));
        
        public static Defaults Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Port 1")]
        public string Port1Name {
            get {
                return ((string)(this["Port1Name"]));
            }
            set {
                this["Port1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Port 2")]
        public string Port2Name {
            get {
                return ((string)(this["Port2Name"]));
            }
            set {
                this["Port2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Port 3")]
        public string Port3Name {
            get {
                return ((string)(this["Port3Name"]));
            }
            set {
                this["Port3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Port 4")]
        public string Port4Name {
            get {
                return ((string)(this["Port4Name"]));
            }
            set {
                this["Port4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short COMPort {
            get {
                return ((short)(this["COMPort"]));
            }
            set {
                this["COMPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short P1FocusOffset {
            get {
                return ((short)(this["P1FocusOffset"]));
            }
            set {
                this["P1FocusOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short P2FocusOffset {
            get {
                return ((short)(this["P2FocusOffset"]));
            }
            set {
                this["P2FocusOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short P3FocusOffset {
            get {
                return ((short)(this["P3FocusOffset"]));
            }
            set {
                this["P3FocusOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short P4FocusOffset {
            get {
                return ((short)(this["P4FocusOffset"]));
            }
            set {
                this["P4FocusOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double P1RAOffset {
            get {
                return ((double)(this["P1RAOffset"]));
            }
            set {
                this["P1RAOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double P2RAOffset {
            get {
                return ((double)(this["P2RAOffset"]));
            }
            set {
                this["P2RAOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double P3RAOffset {
            get {
                return ((double)(this["P3RAOffset"]));
            }
            set {
                this["P3RAOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double P4RAOffset {
            get {
                return ((double)(this["P4RAOffset"]));
            }
            set {
                this["P4RAOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double P1DecOffset {
            get {
                return ((double)(this["P1DecOffset"]));
            }
            set {
                this["P1DecOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double P2DecOffset {
            get {
                return ((double)(this["P2DecOffset"]));
            }
            set {
                this["P2DecOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double P3DecOffset {
            get {
                return ((double)(this["P3DecOffset"]));
            }
            set {
                this["P3DecOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double P4DecOffset {
            get {
                return ((double)(this["P4DecOffset"]));
            }
            set {
                this["P4DecOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double P1RotationOffset {
            get {
                return ((double)(this["P1RotationOffset"]));
            }
            set {
                this["P1RotationOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double P2RotationOffset {
            get {
                return ((double)(this["P2RotationOffset"]));
            }
            set {
                this["P2RotationOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double P3RotationOffset {
            get {
                return ((double)(this["P3RotationOffset"]));
            }
            set {
                this["P3RotationOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double P4RotationOffset {
            get {
                return ((double)(this["P4RotationOffset"]));
            }
            set {
                this["P4RotationOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LEDsOn {
            get {
                return ((bool)(this["LEDsOn"]));
            }
            set {
                this["LEDsOn"] = value;
            }
        }
    }
}
