using System.Configuration;
namespace ASCOM.CameraTemplateProjectCS.Properties
	{
	[SettingsProvider(typeof(ASCOM.SettingsProvider))]
	[ASCOM.DeviceId("ASCOM.CameraTemplateProjectCS.Camera")]
	internal sealed partial class Settings
		{
		// No code is defined here, but the partial class definition adds
		// the attributes to the code generated by Visual Studio and tells
		// the ApplicationSettings class to use ASCOM.SettingsProvider
		// to provide its underlying storage.
		}
	}