echo off
echo Compiling ASCOM Helper type library...
midl /tlb Helper.tlb Helper.idl
echo Making Helper PIA...
tlbimp Helper.tlb /out:ASCOM.Helper.dll /asmversion:1.0.0.0 /keyfile:ASCOM.snk /primary
echo Compiling ASCOM Helper2 type library...
midl /tlb Helper2.tlb Helper2.idl
Echo Making Helper2 PIA...
tlbimp Helper2.tlb /out:ASCOM.Helper2.dll /asmversion:1.0.0.0 /keyfile:ASCOM.snk /primary
del *.h
del *.c

