//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptecHID_FilterWheelAPI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OptecHID_FilterWheelAPI.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Error Set.
        /// </summary>
        internal static string ErrorState_0 {
            get {
                return ResourceManager.GetString("ErrorState_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12VDC Power is Disconnected.
        /// </summary>
        internal static string ErrorState_1 {
            get {
                return ResourceManager.GetString("ErrorState_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Stalled During Move or Home Procedure.
        /// </summary>
        internal static string ErrorState_2 {
            get {
                return ResourceManager.GetString("ErrorState_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter Received in Output/Feature Report.
        /// </summary>
        internal static string ErrorState_3 {
            get {
                return ResourceManager.GetString("ErrorState_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to Home Device While Device is Moving.
        /// </summary>
        internal static string ErrorState_4 {
            get {
                return ResourceManager.GetString("ErrorState_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attemted to Move While Device is Already Moving.
        /// </summary>
        internal static string ErrorState_5 {
            get {
                return ResourceManager.GetString("ErrorState_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to Move Before the Device Has Been Homed.
        /// </summary>
        internal static string ErrorState_6 {
            get {
                return ResourceManager.GetString("ErrorState_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No wheel was detected in the device.
        /// </summary>
        internal static string ErrorState_7 {
            get {
                return ResourceManager.GetString("ErrorState_7", resourceCulture);
            }
        }
    }
}
