//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASCOM.GeminiTelescope.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASCOM.GeminiTelescope.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Gemini Driver.
        /// </summary>
        internal static string AboutGeminiDriver {
            get {
                return ResourceManager.GetString("AboutGeminiDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerate.
        /// </summary>
        internal static string Accelerate {
            get {
                return ResourceManager.GetString("Accelerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerate Joystick Fixed Speed.
        /// </summary>
        internal static string AccJoystick {
            get {
                return ResourceManager.GetString("AccJoystick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Gemini Settings.
        /// </summary>
        internal static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Align.
        /// </summary>
        internal static string Align {
            get {
                return ResourceManager.GetString("Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Speeds Mode.
        /// </summary>
        internal static string AllSpeedsMode {
            get {
                return ResourceManager.GetString("AllSpeedsMode", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ASCOM {
            get {
                object obj = ResourceManager.GetObject("ASCOM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At center speed.
        /// </summary>
        internal static string AtCenterSpeed {
            get {
                return ResourceManager.GetString("AtCenterSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At guide speed.
        /// </summary>
        internal static string AtGuideSpeed {
            get {
                return ResourceManager.GetString("AtGuideSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At slew speed.
        /// </summary>
        internal static string AtSlewSpeed {
            get {
                return ResourceManager.GetString("AtSlewSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate.
        /// </summary>
        internal static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Gemini!.
        /// </summary>
        internal static string CannotConnect {
            get {
                return ResourceManager.GetString("CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot disconnect from telescope.
        /// </summary>
        internal static string CannotDisconnect {
            get {
                return ResourceManager.GetString("CannotDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open pass-through port:.
        /// </summary>
        internal static string CannotOpenPTP {
            get {
                return ResourceManager.GetString("CannotOpenPTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set park coordinates:.
        /// </summary>
        internal static string CannotSetParkCoordinates {
            get {
                return ResourceManager.GetString("CannotSetParkCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This voice may be unusable for announcements. Please try another..
        /// </summary>
        internal static string CannotUseVoice {
            get {
                return ResourceManager.GetString("CannotUseVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking serial port.
        /// </summary>
        internal static string CheckPort {
            get {
                return ResourceManager.GetString("CheckPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM port.
        /// </summary>
        internal static string COMport {
            get {
                return ResourceManager.GetString("COMport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Catalogs.
        /// </summary>
        internal static string ConfigureCatalogs {
            get {
                return ResourceManager.GetString("ConfigureCatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Focuser.
        /// </summary>
        internal static string ConfigureFocuser {
            get {
                return ResourceManager.GetString("ConfigureFocuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Park Position.
        /// </summary>
        internal static string ConfigurePark {
            get {
                return ResourceManager.GetString("ConfigurePark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Telescope.
        /// </summary>
        internal static string ConfigureTelescope {
            get {
                return ResourceManager.GetString("ConfigureTelescope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Gemini on .
        /// </summary>
        internal static string ConnectingToGemini {
            get {
                return ResourceManager.GetString("ConnectingToGemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed:.
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Gemini.
        /// </summary>
        internal static string ConnectToGemini {
            get {
                return ResourceManager.GetString("ConnectToGemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data OK.
        /// </summary>
        internal static string DataOK {
            get {
                return ResourceManager.GetString("DataOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEC.
        /// </summary>
        internal static string DEC {
            get {
                return ResourceManager.GetString("DEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decelerate.
        /// </summary>
        internal static string Decelerate {
            get {
                return ResourceManager.GetString("Decelerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decelerate Joystick Fixed Speed.
        /// </summary>
        internal static string DecJoystick {
            get {
                return ResourceManager.GetString("DecJoystick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default profile was not saved!.
        /// </summary>
        internal static string DefaultProfileNotSaved {
            get {
                return ResourceManager.GetString("DefaultProfileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default profile was saved as &apos;GeminiDefaultProfile.gp&apos;.
        /// </summary>
        internal static string DefaultProfileSavedAsGeminiDefaultProfile {
            get {
                return ResourceManager.GetString("DefaultProfileSavedAsGeminiDefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other programs are still connected. Are you sure you want to disconnect from the mount?.
        /// </summary>
        internal static string DisconnectWarning {
            get {
                return ResourceManager.GetString("DisconnectWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini connection.
        /// </summary>
        internal static string discWarning1 {
            get {
                return ResourceManager.GetString("discWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s are.
        /// </summary>
        internal static string discWarning2 {
            get {
                return ResourceManager.GetString("discWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        internal static string discWarning3 {
            get {
                return ResourceManager.GetString("discWarning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to still active..
        /// </summary>
        internal static string discWarning4 {
            get {
                return ResourceManager.GetString("discWarning4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CENTER.
        /// </summary>
        internal static string dispCENTER {
            get {
                return ResourceManager.GetString("dispCENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAST.
        /// </summary>
        internal static string dispEAST {
            get {
                return ResourceManager.GetString("dispEAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUIDE.
        /// </summary>
        internal static string dispGUIDE {
            get {
                return ResourceManager.GetString("dispGUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIMIT!.
        /// </summary>
        internal static string dispLIMIT {
            get {
                return ResourceManager.GetString("dispLIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARK.
        /// </summary>
        internal static string dispPARK {
            get {
                return ResourceManager.GetString("dispPARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLEW.
        /// </summary>
        internal static string dispSLEW {
            get {
                return ResourceManager.GetString("dispSLEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string dispSTOP {
            get {
                return ResourceManager.GetString("dispSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRACK.
        /// </summary>
        internal static string dispTRACK {
            get {
                return ResourceManager.GetString("dispTRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEST.
        /// </summary>
        internal static string dispWEST {
            get {
                return ResourceManager.GetString("dispWEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Button.
        /// </summary>
        internal static string DownButton {
            get {
                return ResourceManager.GetString("DownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Key.
        /// </summary>
        internal static string DownKey {
            get {
                return ResourceManager.GetString("DownKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini Controller was minimized.
        /// </summary>
        internal static string DriverMinimized {
            get {
                return ResourceManager.GetString("DriverMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini ASCOM controller is still running.
        ///It can be accessed from this icon.
        /// </summary>
        internal static string DriverRunning {
            get {
                return ResourceManager.GetString("DriverRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        internal static string Elevation {
            get {
                return ResourceManager.GetString("Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable Periodic Error Correction (PEC).
        /// </summary>
        internal static string EnablePEC {
            get {
                return ResourceManager.GetString("EnablePEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Menu.
        /// </summary>
        internal static string EnterMenu {
            get {
                return ResourceManager.GetString("EnterMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file.
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing file:.
        /// </summary>
        internal static string ErrorWritingFile {
            get {
                return ResourceManager.GetString("ErrorWritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Menu.
        /// </summary>
        internal static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set Gemini time.
        /// </summary>
        internal static string FailedSetTime {
            get {
                return ResourceManager.GetString("FailedSetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focuser Fast Speed.
        /// </summary>
        internal static string FocuserFast {
            get {
                return ResourceManager.GetString("FocuserFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focuser In.
        /// </summary>
        internal static string FocuserIn {
            get {
                return ResourceManager.GetString("FocuserIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focuser Medium Speed.
        /// </summary>
        internal static string FocuserMedium {
            get {
                return ResourceManager.GetString("FocuserMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focuser Out.
        /// </summary>
        internal static string FocuserOut {
            get {
                return ResourceManager.GetString("FocuserOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focuser Slow Speed.
        /// </summary>
        internal static string FocuserSlow {
            get {
                return ResourceManager.GetString("FocuserSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disconnect and exit?.
        /// </summary>
        internal static string GeminiConnectionAlive1 {
            get {
                return ResourceManager.GetString("GeminiConnectionAlive1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that Gemini default East limit of 114° is too aggressive for most G-11.
        ///
        ///Would you like to set the East limit to a more conservative 98° instead?.
        /// </summary>
        internal static string GeminiG11DefaultSafetyLimitWarning {
            get {
                return ResourceManager.GetString("GeminiG11DefaultSafetyLimitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini is .
        /// </summary>
        internal static string GeminiIs {
            get {
                return ResourceManager.GetString("GeminiIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini is not responding. Please check that it&apos;s connected..
        /// </summary>
        internal static string GeminiNotResponding {
            get {
                return ResourceManager.GetString("GeminiNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Home.
        /// </summary>
        internal static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto failed:.
        /// </summary>
        internal static string GotoFailed {
            get {
                return ResourceManager.GetString("GotoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS.
        /// </summary>
        internal static string GPS {
            get {
                return ResourceManager.GetString("GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Date/Time.
        /// </summary>
        internal static string GPSDateTime {
            get {
                return ResourceManager.GetString("GPSDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS: No position fix.
        /// </summary>
        internal static string GPSNoFix {
            get {
                return ResourceManager.GetString("GPSNoFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Controller Down button.
        /// </summary>
        internal static string HC_DN {
            get {
                return ResourceManager.GetString("HC_DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Controller Left button.
        /// </summary>
        internal static string HC_LF {
            get {
                return ResourceManager.GetString("HC_LF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Controller Menu button.
        /// </summary>
        internal static string HC_MENU {
            get {
                return ResourceManager.GetString("HC_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Controller Right button.
        /// </summary>
        internal static string HC_RT {
            get {
                return ResourceManager.GetString("HC_RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Controller Up button.
        /// </summary>
        internal static string HC_UP {
            get {
                return ResourceManager.GetString("HC_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini Telescope Net Installation and Operation.pdf.
        /// </summary>
        internal static string HelpFileName {
            get {
                return ResourceManager.GetString("HelpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help!.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Hand Controller.
        /// </summary>
        internal static string HideHandController {
            get {
                return ResourceManager.GetString("HideHandController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Notifications.
        /// </summary>
        internal static string HideNotifications {
            get {
                return ResourceManager.GetString("HideNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide status panel.
        /// </summary>
        internal static string HideStatusPanel {
            get {
                return ResourceManager.GetString("HideStatusPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HINT: Press a button on the joystick to see it highlited in the list above..
        /// </summary>
        internal static string HintJoystick {
            get {
                return ResourceManager.GetString("HintJoystick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Alt value.
        /// </summary>
        internal static string InvalidAltValue {
            get {
                return ResourceManager.GetString("InvalidAltValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Az value.
        /// </summary>
        internal static string InvalidAzValue {
            get {
                return ResourceManager.GetString("InvalidAzValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data received.
        /// </summary>
        internal static string InvalidDataReceived {
            get {
                return ResourceManager.GetString("InvalidDataReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following setting(s) are invalid:.
        /// </summary>
        internal static string InvalidSettings {
            get {
                return ResourceManager.GetString("InvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Site Settings.
        /// </summary>
        internal static string InvalidSite {
            get {
                return ResourceManager.GetString("InvalidSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick is not available.
        /// </summary>
        internal static string JoystickIsNotAvailable {
            get {
                return ResourceManager.GetString("JoystickIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick stop.
        /// </summary>
        internal static string JoystickStop {
            get {
                return ResourceManager.GetString("JoystickStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Button.
        /// </summary>
        internal static string LeftButton {
            get {
                return ResourceManager.GetString("LeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Key.
        /// </summary>
        internal static string LeftKey {
            get {
                return ResourceManager.GetString("LeftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit switches off.
        /// </summary>
        internal static string LimitOff {
            get {
                return ResourceManager.GetString("LimitOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit switches on.
        /// </summary>
        internal static string LimitOn {
            get {
                return ResourceManager.GetString("LimitOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meridian Flip.
        /// </summary>
        internal static string MedidianFlip {
            get {
                return ResourceManager.GetString("MedidianFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Meridian Flip.
        /// </summary>
        internal static string MeridianFlip {
            get {
                return ResourceManager.GetString("MeridianFlip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount.
        /// </summary>
        internal static string Mount {
            get {
                return ResourceManager.GetString("Mount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount Declination.
        /// </summary>
        internal static string MountDEC {
            get {
                return ResourceManager.GetString("MountDEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount Hour Angle.
        /// </summary>
        internal static string MountHA {
            get {
                return ResourceManager.GetString("MountHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount is connected.
        /// </summary>
        internal static string MountIsConnected {
            get {
                return ResourceManager.GetString("MountIsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount is disconnected.
        /// </summary>
        internal static string MountIsDisconnected {
            get {
                return ResourceManager.GetString("MountIsDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount Local Sidereal Time.
        /// </summary>
        internal static string MountLST {
            get {
                return ResourceManager.GetString("MountLST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount Right Ascension.
        /// </summary>
        internal static string MountRA {
            get {
                return ResourceManager.GetString("MountRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount stopped.
        /// </summary>
        internal static string MountStopped {
            get {
                return ResourceManager.GetString("MountStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop/Start Tracking.
        /// </summary>
        internal static string MountStopStart {
            get {
                return ResourceManager.GetString("MountStopStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Focuser In.
        /// </summary>
        internal static string MoveFocusIn {
            get {
                return ResourceManager.GetString("MoveFocusIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Focuser Out.
        /// </summary>
        internal static string MoveFocusOut {
            get {
                return ResourceManager.GetString("MoveFocusOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Joystick.
        /// </summary>
        internal static string MoveJoystick {
            get {
                return ResourceManager.GetString("MoveJoystick", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap no_fix_satellite {
            get {
                object obj = ResourceManager.GetObject("no_fix_satellite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap no_satellite {
            get {
                object obj = ResourceManager.GetObject("no_satellite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load profile:.
        /// </summary>
        internal static string NoProfileLoad {
            get {
                return ResourceManager.GetString("NoProfileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save profile:.
        /// </summary>
        internal static string NoProfileSave {
            get {
                return ResourceManager.GetString("NoProfileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Target!.
        /// </summary>
        internal static string NoTarget {
            get {
                return ResourceManager.GetString("NoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not connected.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object below the horizon -- cannot do a meridian flip.
        /// </summary>
        internal static string ObjectBelowHorizon {
            get {
                return ResourceManager.GetString("ObjectBelowHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Search One degree.
        /// </summary>
        internal static string ObjectSearch1 {
            get {
                return ResourceManager.GetString("ObjectSearch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Search Two degrees.
        /// </summary>
        internal static string ObjectSearch2 {
            get {
                return ResourceManager.GetString("ObjectSearch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform a meridian flip: object is unreachable from the other side.
        /// </summary>
        internal static string ObjectUnreachable {
            get {
                return ResourceManager.GetString("ObjectUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Search 1 Degree.
        /// </summary>
        internal static string ObjSrch1 {
            get {
                return ResourceManager.GetString("ObjSrch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Search 2 Degrees.
        /// </summary>
        internal static string ObjSrch2 {
            get {
                return ResourceManager.GetString("ObjSrch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Log.
        /// </summary>
        internal static string ObservationLog {
            get {
                return ResourceManager.GetString("ObservationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to write advanced settings to Gemini.
        ///    
        ///Are you sure you want to do this?.
        /// </summary>
        internal static string OverwriteSettings {
            get {
                return ResourceManager.GetString("OverwriteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park Gemini.
        /// </summary>
        internal static string Park {
            get {
                return ResourceManager.GetString("Park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park at Alt/Az coordinates.
        /// </summary>
        internal static string ParkAtAltAz {
            get {
                return ResourceManager.GetString("ParkAtAltAz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park at Current Mount Position.
        /// </summary>
        internal static string ParkAtCurrent {
            get {
                return ResourceManager.GetString("ParkAtCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park at Start-up Position (CWD).
        /// </summary>
        internal static string ParkAtCWD {
            get {
                return ResourceManager.GetString("ParkAtCWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park at Home Position.
        /// </summary>
        internal static string ParkAtHome {
            get {
                return ResourceManager.GetString("ParkAtHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park at C W D.
        /// </summary>
        internal static string ParkCWD {
            get {
                return ResourceManager.GetString("ParkCWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park Here.
        /// </summary>
        internal static string ParkHere {
            get {
                return ResourceManager.GetString("ParkHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park at Home.
        /// </summary>
        internal static string ParkHome {
            get {
                return ResourceManager.GetString("ParkHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park mount.
        /// </summary>
        internal static string ParkMount {
            get {
                return ResourceManager.GetString("ParkMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Meridian Flip.
        /// </summary>
        internal static string PERF_FLIP {
            get {
                return ResourceManager.GetString("PERF_FLIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Mount Functions.
        /// </summary>
        internal static string PerformFunctions {
            get {
                return ResourceManager.GetString("PerformFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Mode.
        /// </summary>
        internal static string PhotoMode {
            get {
                return ResourceManager.GetString("PhotoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one!.
        /// </summary>
        internal static string PleaseSelectOne {
            get {
                return ResourceManager.GetString("PleaseSelectOne", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass-through port will be disabled.
        /// </summary>
        internal static string PTPDisabled {
            get {
                return ResourceManager.GetString("PTPDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini Pass-Through port # is invalid:.
        /// </summary>
        internal static string PTPInvalid {
            get {
                return ResourceManager.GetString("PTPInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RA.
        /// </summary>
        internal static string RA {
            get {
                return ResourceManager.GetString("RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reboot Gemini controller?.
        /// </summary>
        internal static string RebootController {
            get {
                return ResourceManager.GetString("RebootController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot Gemini.
        /// </summary>
        internal static string RebootGemini {
            get {
                return ResourceManager.GetString("RebootGemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Gemini Observation Log.
        /// </summary>
        internal static string RetrieveGeminiObservationLog {
            get {
                return ResourceManager.GetString("RetrieveGeminiObservationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Button.
        /// </summary>
        internal static string RightButton {
            get {
                return ResourceManager.GetString("RightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Key.
        /// </summary>
        internal static string RightKey {
            get {
                return ResourceManager.GetString("RightKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety limit reached!.
        /// </summary>
        internal static string SafetyLimitReached {
            get {
                return ResourceManager.GetString("SafetyLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new safety limits are more aggressive than the Gemini default.
        ///
        ///Incorrect safety limits can result in hardware damage.
        ///Are you sure you want to use these new values?.
        /// </summary>
        internal static string SafetyLimitsAggressive {
            get {
                return ResourceManager.GetString("SafetyLimitsAggressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Limit set to current position.
        /// </summary>
        internal static string SafetyLimitSet {
            get {
                return ResourceManager.GetString("SafetyLimitSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Limit Warning.
        /// </summary>
        internal static string SafetyLimitWarning {
            get {
                return ResourceManager.GetString("SafetyLimitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RA and DEC are assigned to the same controller axis! Please select different axes..
        /// </summary>
        internal static string SameAxis {
            get {
                return ResourceManager.GetString("SameAxis", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap satellite {
            get {
                object obj = ResourceManager.GetObject("satellite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Gemini.
        /// </summary>
        internal static string SearchForGemini {
            get {
                return ResourceManager.GetString("SearchForGemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Com Port.
        /// </summary>
        internal static string SelectCOMPort {
            get {
                return ResourceManager.GetString("SelectCOMPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial port communication error.
        /// </summary>
        internal static string SerialError {
            get {
                return ResourceManager.GetString("SerialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial port timed out!.
        /// </summary>
        internal static string SerialTimeout {
            get {
                return ResourceManager.GetString("SerialTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Fast Focuser Speed.
        /// </summary>
        internal static string SetFastFocuser {
            get {
                return ResourceManager.GetString("SetFastFocuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Medium Focuser Speed.
        /// </summary>
        internal static string SetMediumFocuser {
            get {
                return ResourceManager.GetString("SetMediumFocuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Slow Focuser Speed.
        /// </summary>
        internal static string SetSlowFocuser {
            get {
                return ResourceManager.GetString("SetSlowFocuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [settings from Gemini].
        /// </summary>
        internal static string SettingsFromGemini {
            get {
                return ResourceManager.GetString("SettingsFromGemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Driver and Gemini.
        /// </summary>
        internal static string SetupDriver {
            get {
                return ResourceManager.GetString("SetupDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup telescope window.
        /// </summary>
        internal static string SetupTelescope {
            get {
                return ResourceManager.GetString("SetupTelescope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hand Controller.
        /// </summary>
        internal static string ShowHandController {
            get {
                return ResourceManager.GetString("ShowHandController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Notifications.
        /// </summary>
        internal static string ShowNotifications {
            get {
                return ResourceManager.GetString("ShowNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show setup focuser window.
        /// </summary>
        internal static string ShowSetupFocuser {
            get {
                return ResourceManager.GetString("ShowSetupFocuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Status Panel.
        /// </summary>
        internal static string ShowStatusPanel {
            get {
                return ResourceManager.GetString("ShowStatusPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slew DEC-.
        /// </summary>
        internal static string SlewDECM {
            get {
                return ResourceManager.GetString("SlewDECM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slew DEC+.
        /// </summary>
        internal static string SlewDECP {
            get {
                return ResourceManager.GetString("SlewDECP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slew RA-.
        /// </summary>
        internal static string SlewRAM {
            get {
                return ResourceManager.GetString("SlewRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slew RA+.
        /// </summary>
        internal static string SlewRAP {
            get {
                return ResourceManager.GetString("SlewRAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some settings are invalid!.
        /// </summary>
        internal static string SomeInvalidSettings {
            get {
                return ResourceManager.GetString("SomeInvalidSettings", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap starfield {
            get {
                object obj = ResourceManager.GetObject("starfield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Tracking.
        /// </summary>
        internal static string StartTracking {
            get {
                return ResourceManager.GetString("StartTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Panel.
        /// </summary>
        internal static string StatusPanel {
            get {
                return ResourceManager.GetString("StatusPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop slew.
        /// </summary>
        internal static string StopSlew {
            get {
                return ResourceManager.GetString("StopSlew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Tracking.
        /// </summary>
        internal static string StopTracking {
            get {
                return ResourceManager.GetString("StopTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap DEC buttons.
        /// </summary>
        internal static string SwapDEC {
            get {
                return ResourceManager.GetString("SwapDEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap RA buttons.
        /// </summary>
        internal static string SwapRA {
            get {
                return ResourceManager.GetString("SwapRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        internal static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini is not responding! Terminating connection..
        /// </summary>
        internal static string TerminatingConnection {
            get {
                return ResourceManager.GetString("TerminatingConnection", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Ticked {
            get {
                object obj = ResourceManager.GetObject("Ticked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Focuser Speed: Slow/Medium/Fast.
        /// </summary>
        internal static string ToggleFocuserSpeed {
            get {
                return ResourceManager.GetString("ToggleFocuserSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle between Visual, All Speed, and Photo modes.
        /// </summary>
        internal static string ToggleVAP {
            get {
                return ResourceManager.GetString("ToggleVAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many serial port errors! Please check Gemini..
        /// </summary>
        internal static string TooManyErrors {
            get {
                return ResourceManager.GetString("TooManyErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpark Gemini.
        /// </summary>
        internal static string Unpark {
            get {
                return ResourceManager.GetString("Unpark", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UnTicked {
            get {
                object obj = ResourceManager.GetObject("UnTicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Button.
        /// </summary>
        internal static string UpButton {
            get {
                return ResourceManager.GetString("UpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Key.
        /// </summary>
        internal static string UpKey {
            get {
                return ResourceManager.GetString("UpKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Centering speed.
        /// </summary>
        internal static string UseCenter {
            get {
                return ResourceManager.GetString("UseCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Guiding speed.
        /// </summary>
        internal static string UseGuide {
            get {
                return ResourceManager.GetString("UseGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Slew speed.
        /// </summary>
        internal static string UseSlew {
            get {
                return ResourceManager.GetString("UseSlew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Mode.
        /// </summary>
        internal static string VisualMode {
            get {
                return ResourceManager.GetString("VisualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for data....
        /// </summary>
        internal static string WaitingForData {
            get {
                return ResourceManager.GetString("WaitingForData", resourceCulture);
            }
        }
    }
}
