//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASCOM.Simulator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Simulated Video Capture Device")]
        public string VideoCaptureDeviceName {
            get {
                return ((string)(this["VideoCaptureDeviceName"]));
            }
            set {
                this["VideoCaptureDeviceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SimulatedAction1#;SimulatedAction2")]
        public string SupportedActionsList {
            get {
                return ((string)(this["SupportedActionsList"]));
            }
            set {
                this["SupportedActionsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.04#;0.08#;0.16#;0.32#;0.64#;1.28#;2.56#;5.12#;10.24")]
        public string SupportedExposuresList {
            get {
                return ((string)(this["SupportedExposuresList"]));
            }
            set {
                this["SupportedExposuresList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double ExposureMax {
            get {
                return ((double)(this["ExposureMax"]));
            }
            set {
                this["ExposureMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.033")]
        public double ExposureMin {
            get {
                return ((double)(this["ExposureMin"]));
            }
            set {
                this["ExposureMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AnalogueNonIntegrating")]
        public global::ASCOM.Simulator.Properties.SiumulatedCameraType CameraType {
            get {
                return ((global::ASCOM.Simulator.Properties.SiumulatedCameraType)(this["CameraType"]));
            }
            set {
                this["CameraType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PAL")]
        public global::ASCOM.Simulator.Properties.AnalogueCameraFrameRate CameraFrameRate {
            get {
                return ((global::ASCOM.Simulator.Properties.AnalogueCameraFrameRate)(this["CameraFrameRate"]));
            }
            set {
                this["CameraFrameRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ICX285AL")]
        public string SensorName {
            get {
                return ((string)(this["SensorName"]));
            }
            set {
                this["SensorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Monochrome")]
        public global::ASCOM.DeviceInterface.SensorType SensorType {
            get {
                return ((global::ASCOM.DeviceInterface.SensorType)(this["SensorType"]));
            }
            set {
                this["SensorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int BitDepth {
            get {
                return ((int)(this["BitDepth"]));
            }
            set {
                this["BitDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SourceBitmapFilesLocation {
            get {
                return ((string)(this["SourceBitmapFilesLocation"]));
            }
            set {
                this["SourceBitmapFilesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AVI")]
        public string VideoFileFormat {
            get {
                return ((string)(this["VideoFileFormat"]));
            }
            set {
                this["VideoFileFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short GainMin {
            get {
                return ((short)(this["GainMin"]));
            }
            set {
                this["GainMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public short GainMax {
            get {
                return ((short)(this["GainMax"]));
            }
            set {
                this["GainMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Gains {
            get {
                return ((string)(this["Gains"]));
            }
            set {
                this["Gains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Gammas {
            get {
                return ((string)(this["Gammas"]));
            }
            set {
                this["Gammas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SupportsGainRange {
            get {
                return ((bool)(this["SupportsGainRange"]));
            }
            set {
                this["SupportsGainRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double PixelSizeX {
            get {
                return ((double)(this["PixelSizeX"]));
            }
            set {
                this["PixelSizeX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double PixelSizeY {
            get {
                return ((double)(this["PixelSizeY"]));
            }
            set {
                this["PixelSizeY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseEmbeddedVideoSource {
            get {
                return ((bool)(this["UseEmbeddedVideoSource"]));
            }
            set {
                this["UseEmbeddedVideoSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseBuffering {
            get {
                return ((bool)(this["UseBuffering"]));
            }
            set {
                this["UseBuffering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public short BufferSize {
            get {
                return ((short)(this["BufferSize"]));
            }
            set {
                this["BufferSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCompressionDialog {
            get {
                return ((bool)(this["ShowCompressionDialog"]));
            }
            set {
                this["ShowCompressionDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SupportsGammaRange {
            get {
                return ((bool)(this["SupportsGammaRange"]));
            }
            set {
                this["SupportsGammaRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short GammaMin {
            get {
                return ((short)(this["GammaMin"]));
            }
            set {
                this["GammaMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public short GammaMax {
            get {
                return ((short)(this["GammaMax"]));
            }
            set {
                this["GammaMax"] = value;
            }
        }
    }
}
